INSERT INTO FOOD (FOOD_NAME, FOOD_RATING) VALUES ('NUTELLA','5');
INSERT INTO FOOD (FOOD_NAME, FOOD_RATING) VALUES ('KITKAT','4');
INSERT INTO FOOD (FOOD_NAME, FOOD_RATING) VALUES ('CHICKEN','5');
INSERT INTO FOOD (FOOD_NAME, FOOD_RATING) VALUES ('Khichdi','1');
INSERT INTO FOOD (FOOD_NAME, FOOD_RATING) VALUES ('Idly','3');
INSERT INTO FOOD (FOOD_NAME, FOOD_RATING) VALUES ('ButterIdly','5');
